baseURL = 'https://michaelcosj.github.io'
languageCode = 'en-us'
title = "Michael's Notebook"
copyright = "michaelcosj"
theme = 'cactus'

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Tech"
  url = "/tech"
  weight = 2

[[menu.main]]
  name = "Stuff"
  url = "/other"
  weight = 3

[[menu.main]]
  name = "Tags"
  url = "/tags"
  weight = 4

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 5

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "native"
    tabWidth = 4

[params]
  colortheme = "light"
  description = "I write code and stuff."
  rss = true
  tocInline = false
  mainSection = "notes"
  mainSectionTitle = "Recent Notes"
  showProjectsList = false
  projectsUrl = "https://github.com/michaelcosj"
  show_updated = true # default
  showReadTime = true # default

  [params.comments]
      enabled = true
      engine = "utterances"
    [params.comments.utterances]
      repo = "michaelcosj/michaelcosj.github.io"
      label = "[ðŸ’¬]-comments"
      theme = "gruvbox-dark"
    [params.comments.cactuscomments]
      siteName = "your_cactus_comments_sitename" # see https://cactus.chat/ on how to register your site name
      #serverUrl = "" # Defaults to https://matrix.cactus.chat:8448 (Cactus Chat public server)
      #serverName = "" # Defaults to cactus.chat

[[params.social]]
  name = "github"
  link = "https://github.com/michaelcosj"

[[params.social]]
  name = "twitter"
  link = "https://twitter.com/michaelcosj"

[[params.social]]
  name = "email"
  link = "michaelcosj@protonmail.com"

